"""Poor Man's Covered Call (PMCC) strategy implementation.

A PMCC is a synthetic covered call that replaces the long stock position
with a deep ITM LEAPS call, reducing capital requirements while maintaining
similar P&L characteristics.  The trade consists of:

- **Buy** a deep ITM LEAPS call (delta 0.75--0.85, DTE 270--540)
- **Sell** an OTM near-term call (delta 0.25--0.35, DTE 21--45)

The strategy generates income by repeatedly selling short-dated calls
against the LEAPS position.  When the short call nears expiry, it is
rolled forward to a new cycle.

This strategy is selected in low-volatility trending or high-volatility
trending regimes when IV Rank is below 50.

Usage::

    from src.strategies.base import StrategyConfig
    from src.strategies.pmcc import PoorMansCC

    config = StrategyConfig(
        enabled=True,
        regimes=["low_vol_trend", "high_vol_trend"],
        min_iv_rank=0,
        max_iv_rank=50,
        delta_range={"leaps": [0.75, 0.85], "short_call": [0.25, 0.35]},
        target_dte={"leaps": 365, "short_call": 30},
        dte_range={"leaps": [270, 540], "short_call": [21, 45]},
        profit_target_pct=0.30,
        stop_loss_pct=0.20,
        max_positions=2,
    )
    strategy = PoorMansCC(config)
"""

from __future__ import annotations

from datetime import date
from typing import Any

from src.strategies.base import (
    BaseStrategy,
    Direction,
    ExitReason,
    ExitSignal,
    GreeksSnapshot,
    LegSpec,
    OptionData,
    StrategyConfig,
    TradeRecord,
    TradeSignal,
)
from src.utils.logging import get_logger

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Default delta ranges for the LEAPS and short call legs.
_DEFAULT_LEAPS_DELTA_MIN: float = 0.75
_DEFAULT_LEAPS_DELTA_MAX: float = 0.85
_DEFAULT_SHORT_CALL_DELTA_MIN: float = 0.25
_DEFAULT_SHORT_CALL_DELTA_MAX: float = 0.35

# Default DTE ranges.
_DEFAULT_LEAPS_DTE_MIN: int = 270
_DEFAULT_LEAPS_DTE_MAX: int = 540
_DEFAULT_SHORT_CALL_DTE_MIN: int = 21
_DEFAULT_SHORT_CALL_DTE_MAX: int = 45

# Default DTE at which to roll the short call.
_DEFAULT_ROLL_SHORT_AT_DTE: int = 7

# Exit if underlying drops below this fraction of entry price.
_UNDERLYING_DROP_THRESHOLD: float = 0.90

# Options multiplier (standard US equity options).
_MULTIPLIER: int = 100


class PoorMansCC(BaseStrategy):
    """Poor Man's Covered Call: buy deep ITM LEAPS + sell OTM short call.

    A synthetic covered call that uses a deep ITM LEAPS call as the
    long stock substitute.  Income is generated by selling near-term OTM
    calls against the LEAPS.  The short call is rolled when its DTE drops
    below the configured roll threshold.

    Args:
        config: Strategy configuration from ``config/strategies.yaml``.
    """

    def __init__(self, config: StrategyConfig) -> None:
        super().__init__(config)
        self._log = get_logger(f"strategy.{self.name}")

        # Extract delta ranges from config, falling back to defaults.
        delta_cfg = self._config.delta_range
        leaps_range = delta_cfg.get(
            "leaps",
            [_DEFAULT_LEAPS_DELTA_MIN, _DEFAULT_LEAPS_DELTA_MAX],
        )
        short_range = delta_cfg.get(
            "short_call",
            [_DEFAULT_SHORT_CALL_DELTA_MIN, _DEFAULT_SHORT_CALL_DELTA_MAX],
        )

        if isinstance(leaps_range, list) and len(leaps_range) == 2:
            self._leaps_delta_min: float = float(leaps_range[0])
            self._leaps_delta_max: float = float(leaps_range[1])
        else:
            self._leaps_delta_min = _DEFAULT_LEAPS_DELTA_MIN
            self._leaps_delta_max = _DEFAULT_LEAPS_DELTA_MAX

        if isinstance(short_range, list) and len(short_range) == 2:
            self._short_call_delta_min: float = float(short_range[0])
            self._short_call_delta_max: float = float(short_range[1])
        else:
            self._short_call_delta_min = _DEFAULT_SHORT_CALL_DELTA_MIN
            self._short_call_delta_max = _DEFAULT_SHORT_CALL_DELTA_MAX

        # Extract DTE ranges.
        dte_range_cfg = self._config.dte_range
        if isinstance(dte_range_cfg, dict):
            leaps_dte = dte_range_cfg.get(
                "leaps", [_DEFAULT_LEAPS_DTE_MIN, _DEFAULT_LEAPS_DTE_MAX]
            )
            short_dte = dte_range_cfg.get(
                "short_call",
                [_DEFAULT_SHORT_CALL_DTE_MIN, _DEFAULT_SHORT_CALL_DTE_MAX],
            )
        else:
            leaps_dte = [_DEFAULT_LEAPS_DTE_MIN, _DEFAULT_LEAPS_DTE_MAX]
            short_dte = [_DEFAULT_SHORT_CALL_DTE_MIN, _DEFAULT_SHORT_CALL_DTE_MAX]

        if isinstance(leaps_dte, list) and len(leaps_dte) == 2:
            self._leaps_dte_min: int = int(leaps_dte[0])
            self._leaps_dte_max: int = int(leaps_dte[1])
        else:
            self._leaps_dte_min = _DEFAULT_LEAPS_DTE_MIN
            self._leaps_dte_max = _DEFAULT_LEAPS_DTE_MAX

        if isinstance(short_dte, list) and len(short_dte) == 2:
            self._short_call_dte_min: int = int(short_dte[0])
            self._short_call_dte_max: int = int(short_dte[1])
        else:
            self._short_call_dte_min = _DEFAULT_SHORT_CALL_DTE_MIN
            self._short_call_dte_max = _DEFAULT_SHORT_CALL_DTE_MAX

        # Roll threshold: roll the short call when DTE drops below this.
        self._roll_short_at_dte: int = (
            self._config.roll_short_at_dte
            if self._config.roll_short_at_dte is not None
            else _DEFAULT_ROLL_SHORT_AT_DTE
        )

    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------

    @property
    def name(self) -> str:
        """Return the canonical strategy name."""
        return "pmcc"

    # ------------------------------------------------------------------
    # Entry evaluation
    # ------------------------------------------------------------------

    async def check_entry(
        self,
        ticker: str,
        spot_price: float,
        iv_rank: float,
        regime: str,
        greeks: GreeksSnapshot,
        options_chain: list[OptionData],
    ) -> TradeSignal | None:
        """Evaluate whether to open a PMCC position.

        Steps:
        1. Verify eligibility (regime, IV rank, underlying price).
        2. Find the LEAPS call (deep ITM, delta 0.75--0.85, DTE 270--540).
        3. Find the short call (OTM, delta 0.25--0.35, DTE 21--45).
        4. Validate bid-ask spreads and open interest.
        5. Ensure the LEAPS extrinsic value is acceptable.
        6. Calculate net debit, max profit per cycle, and max loss.

        Args:
            ticker: Underlying symbol.
            spot_price: Current price of the underlying.
            iv_rank: IV Rank (0--100).
            regime: Current market regime.
            greeks: Aggregate Greeks snapshot.
            options_chain: Available options with Greeks and prices.

        Returns:
            A :class:`TradeSignal` if entry criteria are met, or ``None``.
        """
        if not self.is_eligible(regime, iv_rank, spot_price):
            return None

        self._log.info(
            "evaluating_entry",
            ticker=ticker,
            spot_price=spot_price,
            iv_rank=iv_rank,
            regime=regime,
        )

        # Construct legs (handles all validation internally).
        try:
            legs = self.construct_legs(spot_price, options_chain)
        except ValueError as exc:
            self._log.debug(
                "leg_construction_failed",
                ticker=ticker,
                error=str(exc),
            )
            return None

        # Identify the LEAPS (buy) and short call (sell) legs.
        leaps_leg = next((leg for leg in legs if leg.action == "BUY"), None)
        short_call_leg = next((leg for leg in legs if leg.action == "SELL"), None)

        if leaps_leg is None or short_call_leg is None:
            self._log.warning(
                "invalid_legs",
                ticker=ticker,
                num_legs=len(legs),
            )
            return None

        # Net premium is positive (debit: LEAPS cost - short call credit).
        net_premium = leaps_leg.mid_price - short_call_leg.mid_price

        if net_premium <= 0:
            self._log.debug(
                "invalid_premium",
                ticker=ticker,
                net_premium=net_premium,
                leaps_price=leaps_leg.mid_price,
                short_price=short_call_leg.mid_price,
            )
            return None

        # Ensure LEAPS is deep enough ITM: the extrinsic value should
        # be reasonable (LEAPS intrinsic = spot - LEAPS_strike for ITM call).
        leaps_intrinsic = max(0.0, spot_price - leaps_leg.strike)
        leaps_extrinsic = leaps_leg.mid_price - leaps_intrinsic

        if leaps_extrinsic > leaps_leg.mid_price * 0.30:
            self._log.debug(
                "leaps_extrinsic_too_high",
                ticker=ticker,
                leaps_mid=leaps_leg.mid_price,
                intrinsic=round(leaps_intrinsic, 2),
                extrinsic=round(leaps_extrinsic, 2),
                extrinsic_pct=round(leaps_extrinsic / leaps_leg.mid_price, 4),
            )
            return None

        max_profit = self.calculate_max_profit(legs, net_premium)
        max_loss = self.calculate_max_loss(legs, net_premium)

        self._log.info(
            "entry_signal_generated",
            ticker=ticker,
            leaps_strike=leaps_leg.strike,
            leaps_expiry=str(leaps_leg.expiry),
            short_call_strike=short_call_leg.strike,
            short_call_expiry=str(short_call_leg.expiry),
            net_debit=round(net_premium, 4),
            max_profit_per_cycle=round(max_profit, 2),
            max_loss=round(max_loss, 2),
        )

        return TradeSignal(
            strategy=self.name,
            ticker=ticker,
            direction=Direction.LONG,
            legs=legs,
            net_premium=round(net_premium, 4),
            max_profit=round(max_profit, 2),
            max_loss=round(max_loss, 2),
            regime=regime,
            iv_rank=iv_rank,
            reasoning=(
                f"PMCC on {ticker}: buy {leaps_leg.strike}C LEAPS "
                f"(exp {leaps_leg.expiry}) / sell {short_call_leg.strike}C "
                f"(exp {short_call_leg.expiry}) for ${net_premium:.2f} net debit. "
                f"Per-cycle max profit ${max_profit:.2f}, max loss ${max_loss:.2f}. "
                f"Regime: {regime}, IV Rank: {iv_rank:.1f}."
            ),
        )

    # ------------------------------------------------------------------
    # Exit evaluation
    # ------------------------------------------------------------------

    async def check_exit(
        self,
        trade: TradeRecord,
        spot_price: float,
        current_pnl: float,
        current_pnl_pct: float,
        dte_remaining: int,
        greeks: GreeksSnapshot,
    ) -> ExitSignal | None:
        """Evaluate whether to close or roll a PMCC position.

        Checks mechanical exits first, then applies strategy-specific rules:

        - Per-cycle profit target: 30% of short call credit.
        - Stop loss: 20% of LEAPS cost.
        - Roll short call when DTE < 7 (configurable via roll_short_at_dte).
        - Exit if underlying drops below 90% of entry price.

        The roll mechanism returns a special exit signal with urgency 2 and
        metadata indicating a roll should be executed rather than a full close.

        Args:
            trade: The open trade to evaluate.
            spot_price: Current price of the underlying.
            current_pnl: Unrealised P&L in dollars.
            current_pnl_pct: Unrealised P&L as fraction of max values.
            dte_remaining: Days to expiration of the short call.
            greeks: Current Greeks of the position.

        Returns:
            An :class:`ExitSignal` if exit criteria are met, or ``None``.
        """
        # Check shared mechanical exit rules first (profit target, stop loss).
        # Note: the DTE check in mechanical exit applies to the short call.
        # For PMCC we handle DTE-based rolling separately below.
        mechanical = self.check_mechanical_exit(
            trade=trade,
            current_pnl=current_pnl,
            current_pnl_pct=current_pnl_pct,
            dte_remaining=dte_remaining,
        )
        if mechanical is not None:
            # If the mechanical exit is a DTE limit, check if this is
            # actually a roll opportunity rather than a full exit.
            if mechanical.reason == ExitReason.DTE_LIMIT:
                return self._build_roll_signal(trade, dte_remaining)
            return mechanical

        # Strategy-specific: roll the short call when DTE drops below threshold.
        if dte_remaining <= self._roll_short_at_dte:
            return self._build_roll_signal(trade, dte_remaining)

        # Strategy-specific: exit if underlying drops below 90% of entry price.
        entry_price = trade.entry_price
        if entry_price > 0:
            # Use the LEAPS leg entry spot if available, otherwise estimate.
            leaps_leg = next((leg for leg in trade.legs if leg.action == "BUY"), None)
            if leaps_leg is not None:
                # The entry spot is roughly the LEAPS strike + LEAPS premium
                # for a deep ITM call. Use the trade entry_price as a proxy.
                estimated_entry_spot = leaps_leg.strike + leaps_leg.mid_price
                price_floor = estimated_entry_spot * _UNDERLYING_DROP_THRESHOLD

                if spot_price < price_floor:
                    self._log.info(
                        "exit_underlying_below_threshold",
                        trade_id=str(trade.id),
                        ticker=trade.ticker,
                        spot_price=spot_price,
                        price_floor=round(price_floor, 2),
                        threshold_pct=_UNDERLYING_DROP_THRESHOLD,
                    )
                    return ExitSignal(
                        trade_id=trade.id,
                        reason=ExitReason.STRATEGY_SPECIFIC,
                        details=(
                            f"Underlying ${spot_price:.2f} dropped below "
                            f"{_UNDERLYING_DROP_THRESHOLD:.0%} of estimated entry "
                            f"(${price_floor:.2f}). Closing PMCC to limit losses."
                        ),
                        urgency=4,
                    )

        return None

    # ------------------------------------------------------------------
    # Leg construction
    # ------------------------------------------------------------------

    def construct_legs(
        self,
        spot_price: float,
        options_chain: list[OptionData],
        **kwargs: Any,
    ) -> list[LegSpec]:
        """Construct the two legs of a PMCC.

        Searches the options chain for:
        1. A deep ITM LEAPS call (delta 0.75--0.85, DTE 270--540).
        2. A near-term OTM call (delta 0.25--0.35, DTE 21--45).

        The LEAPS provides the long stock substitute, and the short call
        provides income via premium collection.

        Args:
            spot_price: Current underlying price.
            options_chain: Available options to search.
            **kwargs: Unused.

        Returns:
            List of two :class:`LegSpec` objects: [leaps_call, short_call].

        Raises:
            ValueError: If suitable options cannot be found.
        """
        # Partition the chain by DTE range for LEAPS and short call.
        leaps_candidates: list[OptionData] = []
        short_candidates: list[OptionData] = []

        today = date.today()

        for opt in options_chain:
            if opt.right != "C":
                continue

            dte = (opt.expiry - today).days

            if self._leaps_dte_min <= dte <= self._leaps_dte_max:
                leaps_candidates.append(opt)
            elif self._short_call_dte_min <= dte <= self._short_call_dte_max:
                short_candidates.append(opt)

        # Find LEAPS call by delta.
        leaps_call = self.find_option_by_delta(
            options=leaps_candidates,
            right="C",
            target_delta_min=self._leaps_delta_min,
            target_delta_max=self._leaps_delta_max,
        )
        if leaps_call is None:
            raise ValueError(
                f"No LEAPS call found with delta in "
                f"[{self._leaps_delta_min}, {self._leaps_delta_max}] "
                f"and DTE in [{self._leaps_dte_min}, {self._leaps_dte_max}]. "
                f"LEAPS candidates available: {len(leaps_candidates)}"
            )

        if not self.validate_bid_ask_spread(leaps_call):
            raise ValueError(
                f"LEAPS call at strike {leaps_call.strike} has excessive "
                f"bid-ask spread: bid={leaps_call.bid}, ask={leaps_call.ask}"
            )

        # Find short call by delta.
        short_call = self.find_option_by_delta(
            options=short_candidates,
            right="C",
            target_delta_min=self._short_call_delta_min,
            target_delta_max=self._short_call_delta_max,
        )
        if short_call is None:
            raise ValueError(
                f"No short call found with delta in "
                f"[{self._short_call_delta_min}, {self._short_call_delta_max}] "
                f"and DTE in [{self._short_call_dte_min}, {self._short_call_dte_max}]. "
                f"Short call candidates available: {len(short_candidates)}"
            )

        if not self.validate_bid_ask_spread(short_call):
            raise ValueError(
                f"Short call at strike {short_call.strike} has excessive "
                f"bid-ask spread: bid={short_call.bid}, ask={short_call.ask}"
            )

        # Validate the trade makes sense: short call strike must be above
        # the LEAPS strike (otherwise there is no room for profit).
        if short_call.strike <= leaps_call.strike:
            raise ValueError(
                f"Short call strike ({short_call.strike}) must be above "
                f"LEAPS strike ({leaps_call.strike})"
            )

        # Validate the LEAPS is deep ITM.
        if leaps_call.strike >= spot_price:
            raise ValueError(
                f"LEAPS call strike ({leaps_call.strike}) must be below "
                f"spot price ({spot_price}) for deep ITM requirement"
            )

        self._log.debug(
            "legs_constructed",
            leaps_strike=leaps_call.strike,
            leaps_delta=leaps_call.delta,
            leaps_mid=leaps_call.mid_price,
            leaps_expiry=str(leaps_call.expiry),
            short_call_strike=short_call.strike,
            short_call_delta=short_call.delta,
            short_call_mid=short_call.mid_price,
            short_call_expiry=str(short_call.expiry),
        )

        return [
            LegSpec(
                action="BUY",
                right="C",
                strike=leaps_call.strike,
                expiry=leaps_call.expiry,
                quantity=1,
                mid_price=leaps_call.mid_price,
            ),
            LegSpec(
                action="SELL",
                right="C",
                strike=short_call.strike,
                expiry=short_call.expiry,
                quantity=1,
                mid_price=short_call.mid_price,
            ),
        ]

    # ------------------------------------------------------------------
    # Profit / Loss calculation
    # ------------------------------------------------------------------

    def calculate_max_profit(self, legs: list[LegSpec], net_premium: float) -> float:
        """Calculate maximum profit per cycle for a PMCC.

        Per-cycle max profit = short call credit + price appreciation
        up to the short strike, capped by the spread width.

        In practice, per-cycle profit = short call premium x multiplier,
        since the LEAPS retains its value and the short call decays.

        Args:
            legs: The two legs [leaps_call, short_call].
            net_premium: Net debit paid (positive number).

        Returns:
            Per-cycle maximum profit in dollars (positive).
        """
        short_call_leg = next((leg for leg in legs if leg.action == "SELL"), None)
        leaps_leg = next((leg for leg in legs if leg.action == "BUY"), None)

        if short_call_leg is None or leaps_leg is None:
            return 0.0

        # Max profit per cycle: if underlying goes to short strike,
        # profit = (short_strike - leaps_strike - net_debit) * multiplier.
        # But per-cycle max is capped at: short call credit + any appreciation.
        spread_width = short_call_leg.strike - leaps_leg.strike
        max_profit = (spread_width - net_premium) * _MULTIPLIER

        if max_profit < 0:
            # If the debit exceeds the spread width, per-cycle max profit
            # is just the short call credit captured through decay.
            max_profit = short_call_leg.mid_price * _MULTIPLIER

        return round(max_profit, 2)

    def calculate_max_loss(self, legs: list[LegSpec], net_premium: float) -> float:
        """Calculate maximum loss for a PMCC.

        Max loss = net debit of LEAPS minus all credits collected.

        For the initial entry, max loss = (LEAPS cost - short call credit)
        x multiplier = net_premium x multiplier.

        This occurs if the underlying drops to zero and the LEAPS becomes
        worthless.

        Args:
            legs: The two legs [leaps_call, short_call].
            net_premium: Net debit paid (positive number).

        Returns:
            Maximum loss in dollars (positive number).
        """
        max_loss = abs(net_premium) * _MULTIPLIER
        return round(max_loss, 2)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _build_roll_signal(
        self,
        trade: TradeRecord,
        dte_remaining: int,
    ) -> ExitSignal:
        """Build an exit signal that indicates a short call roll.

        Instead of fully closing the PMCC, this signal instructs the
        execution layer to close the short call and open a new one at
        the next cycle's expiration.

        Args:
            trade: The open trade.
            dte_remaining: Current DTE of the short call.

        Returns:
            An :class:`ExitSignal` with roll metadata.
        """
        self._log.info(
            "roll_short_call",
            trade_id=str(trade.id),
            ticker=trade.ticker,
            dte_remaining=dte_remaining,
            roll_threshold=self._roll_short_at_dte,
        )

        return ExitSignal(
            trade_id=trade.id,
            reason=ExitReason.STRATEGY_SPECIFIC,
            details=(
                f"Short call DTE ({dte_remaining}) at or below roll threshold "
                f"({self._roll_short_at_dte}). Roll short call to next cycle."
            ),
            urgency=2,
        )
